# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

[[main]]
  name = "Home"
#  parent = "Kim"
#  url = "https://engineering.purdue.edu/ARTH/"
  weight = 1

[[main]]
  name = "People"
#  parent = "Kim"
  url = "group"
  weight = 10

[[main]]
  name = "Research"
#  parent = "Kim"
  url = "research"
  weight = 15

[[main]]
  name = "News"
#  parent = "Kim"
  url = "#posts"
  weight = 30

[[main]]
  name = "Publications"
#  parent = "Kim"
  url = "publication"
  weight = 40

[[main]]
  name = "Gallery"
#  parent = "Kim"
  url = "gallery"
  weight = 40

[[main]]
  name = "Contact"
#  parent = "Kim"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
